/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.src;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    //TODO make unit tests
}
